- job:
    name: grenade-dsvm-ceilometer
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-dsvm-ceilometer/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-ceilometer/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/ceilometer

- project:
    name: openstack/ceilometer
    check:
      jobs:
        - grenade-dsvm-ceilometer:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - telemetry-dsvm-integration
        # TripleO jobs that deploy Telemetry.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario00(1|2)-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario001-multinode-oooq:
            voting: false
        - tripleo-ci-centos-7-scenario001-multinode-oooq-container:
            voting: false
        - tripleo-ci-centos-7-scenario002-multinode-oooq:
            voting: false
        - tripleo-ci-centos-7-scenario002-multinode-oooq-container:
            voting: false
    gate:
      jobs:
        - grenade-dsvm-ceilometer:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - telemetry-dsvm-integration
