- job:
    name: grenade-dsvm-ceilometer
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-dsvm-ceilometer/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-ceilometer/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/ceilometer

- job:
    name: telemetry-dsvm-integration-ceilometer
    parent: legacy-dsvm-base
    run: playbooks/legacy/telemetry-dsvm-integration-ceilometer/run.yaml
    post-run: playbooks/legacy/telemetry-dsvm-integration-ceilometer/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/panko
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- project:
    name: openstack/ceilometer
    check:
      jobs:
        - grenade-dsvm-ceilometer:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - telemetry-dsvm-integration-ceilometer
    gate:
      jobs:
        - grenade-dsvm-ceilometer:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - telemetry-dsvm-integration-ceilometer
